### ISSUE TITLE
Download Photo Script doesn't work in Python 3.9

### ISSUE THREAD

**Issue by westernguy2** [Cal-CS-61A-Staff/seating#17]
I believe the `encoding` argument in `json.loads` is deprecated, and it's completely removed in Python 3.9.

**Comment by mehrdadn** [comment]
I pushed an [update](/Cal-CS-61A-Staff/seating/commit/6d3685222be797cd8fc29f19779b95eba4cf70ca), see if this works?

**Comment by mehrdadn** [comment]
Closing this issue on the assumption that it works. If you still see issues please let me know.
