### ISSUE TITLE
Student photos (on mouseover) can be cut off at the bottom of the screen

### ISSUE THREAD

**Issue by aegamesi** [Cal-CS-61A-Staff/seating#2]
If you have a large room (like Wheeler), mousing over a seat circle in the seating chart brings up a tooltip with name/photo/SID that can be cut off by the bottom of the window.

I suppose correct behavior in this case would be to show the tooltip/mouseover/whatever above the cursor (rather than below) if there isn't enough space at the bottom of the window.

**Comment by itsnshaw** [comment]
fixed 3876089d407b4f4d9fc4231ea4b7086de14d6bcd
